Oclif core migration
heroku/heroku-cli-command pull request #89
Opened 2022-11-14 16:06 UTC by jheikes515

2022-11-21 15:43 UTC, k80bowman commented on src/api-client.ts
> +    const self = this as any
Perhaps not a question for this PR, but I'm curious as to why we are opting out of type checking here.

2022-11-21 16:25 UTC, k80bowman requested changes
This is looking really great! I do have a few comments, questions, and requests, though.

2022-11-21 16:25 UTC, k80bowman commented on src/completions.ts
> +        .filter((t: any) => t) as string[]
```suggestion
        .filter((t: string | boolean) => t) as string[]
```
The type `string | boolean` seems to work here, might be better to use that.

2022-11-21 16:25 UTC, k80bowman commented on src/flags/pipeline.ts
> +export const pipeline = Flags.build({
Shouldn't this be `Flags.custom`?

2022-11-21 16:25 UTC, k80bowman commented on src/flags/team.ts
> +export const team = (flagArgs: Partial<CompletableOptionFlag<string>> = {}) => teamWithoutCompletion({...flagArgs, completion: TeamCompletion})
It might be good to add a note here the way you did in the flags/app.ts file explaining why you are using this approach, since it's in a separate file.

2022-11-21 16:25 UTC, k80bowman commented on src/login.ts
> +    } catch (error: any) {
Could we use the same approach here as on lines 66-68 to avoid the `error: any`?

2022-11-21 16:25 UTC, k80bowman commented on src/login.ts
> +      } catch (error: any) {
Same comment here, can we avoid the `error: any`?

2022-11-21 16:25 UTC, k80bowman commented on src/login.ts
> +    } catch (error: any) {
Same comment

2022-11-21 16:25 UTC, k80bowman commented on src/login.ts
> +    for (const host of hosts) {
I'm curious about the switch here from a `forEach` to a `for of` loop. Is there a reason for the change?

2022-11-21 16:25 UTC, k80bowman commented on src/login.ts
> +    } catch (error: any) {
Again, can we please avoid `error: any`?

2022-11-21 16:25 UTC, k80bowman commented on src/vars.ts
> +
Are all of the extra lines in this file necessary? Not sure this should be included in this PR.

2022-11-21 16:25 UTC, k80bowman commented on test/api-client.test.ts
> +// tslint:disable no-http-string
It looks like the only reason to disable this rule here is because we added a nocked api call to `http://localhost:5000` on line 105. Out of curiosity, could we change that to `https://api.heroku.com`, which is what the rest of the tests use? That way we wouldn't have to disable this rule.

2022-11-21 16:25 UTC, k80bowman commented on test/flags/app.test.ts
> +    // @ts-ignore
why are we ignoring this next line? (and line 171) If this is necessary, could you please add a comment explaining why for future reference?

2022-11-21 16:25 UTC, k80bowman commented on test/login.test.ts
> +      {scope: ['global'], description: /^Heroku CLI login from .*/, expires_in: 12_345})
This is interesting, why add the underscore?

2022-11-21 16:33 UTC, jheikes515 commented on .github/workflows/ci.yml
>      runs-on: windows-latest
When we migrated to GHA, this was left to run only on Windows since that's all that was tested before, but it should probably be updated to run on MacOS and Ubuntu as well.

2022-11-21 16:36 UTC, jheikes515 commented on package.json
> +    "cli-ux": "^6.0.9",
cli-ux is now part of CliUx, included in core, so this should be deleted, unless the new namespace doesn't work here?

2022-11-21 16:37 UTC, jheikes515 commented on package.json
>      "@oclif/tslint": "^3.1.1",
Was a decision made to leave the old TSLint in place? Otherwise, core includes ESLint, so this could be deleted.

2022-11-21 16:43 UTC, k80bowman commented
One other comment I wanted to leave. I ran the tests locally and I'm getting a type error in the linting that says `The 'deprecation' rule threw an error in '/Users/katy.bowman/Projects/heroku-cli-command/src/file.ts':
TypeError: message.trim is not a function`. However, `message.trim` is not used directly in that file, so I'm not sure what's going on there.

2022-11-21 17:21 UTC, ryandagg commented on src/api-client.ts
> +    const self = this as any
I am also curious. My guess is deadlines, but this might be an interesting case.

2022-11-21 17:26 UTC, ryandagg commented on src/login.ts
> +    } catch (error: any) {
Error catching seems to be an acceptable case for `any`. I don't understand all of the unexpected things that can end up in a `catch`.  I'm reading up on it now.

2022-11-21 17:27 UTC, ryandagg commented on src/vars.ts
> +
I think they were introduced by the eslint rules and were not fully reverted. I do think this is much more readable.

2022-11-21 17:31 UTC, ryandagg commented on test/api-client.test.ts
> +// tslint:disable no-http-string
We (you, Jennette, and I) didn't add a nock call. Anything with `http` will trigger this lint rule, and getting localhost to work with `https` seems out of scope. I would prefer not to change the original tests unless we are sure we know what we're doing.

2022-11-21 17:35 UTC, ryandagg commented on test/api-client.test.ts
> +// tslint:disable no-http-string
I will move the disable to the narrowest scope.

2022-11-21 18:39 UTC, k80bowman commented on test/api-client.test.ts
> +// tslint:disable no-http-string
That works, thanks.

2022-11-21 18:40 UTC, k80bowman commented on src/api-client.ts
> +    const self = this as any
Something to note for cleanup later.

2022-11-21 19:38 UTC, jheikes515 commented on src/flags/pipeline.ts
> +export const pipeline = Flags.build({
+1

2022-11-21 19:55 UTC, jheikes515 commented on src/mutex.ts
> +export type PromiseResolve<T> = (value: T | PromiseLike<T>) => void
Are we sure this won't be undefined?

2022-11-21 19:57 UTC, jheikes515 commented on src/vars.ts
> +
I'm guessing the IDE put them there with Prettier or the linting process? IMO it doesn't hurt anything so I'm OK with it.

2022-11-21 20:13 UTC, jheikes515 commented on test/login.test.ts
> +      {scope: ['global'], description: /^Heroku CLI login from .*/, expires_in: 12_345})
It's a numeric separator - I'm guessing it was added in linting or by Prettier.

2022-11-21 20:14 UTC, jheikes515 reviewed
I can't approve since I started the PR, but looks good to me, with a few questions (no stoppers)

2022-11-30 17:39 UTC, ryandagg commented on test/login.test.ts
> +      {scope: ['global'], description: /^Heroku CLI login from .*/, expires_in: 12_345})
Test pass without it. My guess is an unintentional keystroke. Will revert.

2022-11-30 17:41 UTC, ryandagg commented on package.json
> +    "cli-ux": "^6.0.9",
`cli-ux` is included because it seems that we want to preserve this depreciation, though I'm not sure how we can be certain.
https://github.com/heroku/heroku-cli-command/blob/a2f6a654bf7bbc582c7762bcaceb54102e0a6e68/src/command.ts#L9

2022-11-30 17:44 UTC, ryandagg commented on package.json
>      "@oclif/tslint": "^3.1.1",
Katy and I made the decision to revert eslint inclusion from the scope of this project during your vacation. I believe are thinking was that it isn't needed and makes delivering this project harder.

2022-11-30 17:47 UTC, ryandagg commented on src/mutex.ts
> +export type PromiseResolve<T> = (value: T | PromiseLike<T>) => void
I had initially left a comment on this in GH, but I am not sure where it went.
The updated definition was taken directly from /node_modules/typescript/lib/lib.es5.d.ts 
ln 1498.

2022-11-30 17:58 UTC, ryandagg commented on src/flags/pipeline.ts
> +export const pipeline = Flags.build({
Updated.

2022-11-30 17:58 UTC, ryandagg commented on src/login.ts
> +    } catch (error: any) {
We discussed and decided this was acceptable.

2022-11-30 17:58 UTC, ryandagg commented on src/login.ts
> +      } catch (error: any) {
We discussed and decided this was acceptable.

2022-11-30 17:58 UTC, ryandagg commented on src/login.ts
> +    } catch (error: any) {
We discussed and decided this was acceptable.

2022-11-30 17:58 UTC, ryandagg commented on src/login.ts
> +    for (const host of hosts) {
Reverted.

2022-11-30 17:58 UTC, ryandagg commented on src/login.ts
> +    } catch (error: any) {
We discussed and decided this was acceptable.

2022-12-06 19:07 UTC, merged